// Code generated by Kitex v1.4.1. DO NOT EDIT.

package echo

import (
	"github.com/cloudwego/kitex/server"
	"github.com/teamgram/proto/example/example"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler example.TLExampleEcho, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
