// Code generated by Kitex v1.4.1. DO NOT EDIT.

package echo

import (
	"github.com/cloudwego/kitex/server"
	"github.com/teamgram/proto/example/example"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler example.RPCEcho, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
