//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'mtprotoc'
//
// Copyright (c) 2024-present,  Teamgram Authors.
//  All rights reserved.
//
// Author: Benqi (wubenqi@gmail.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: schema.tl.core_types.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bool <--
//   - TL_boolFalse
//   - TL_boolTrue
type Bool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *Bool) Reset() {
	*x = Bool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bool) ProtoMessage() {}

func (x *Bool) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bool.ProtoReflect.Descriptor instead.
func (*Bool) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{0}
}

func (x *Bool) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Bool) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

type TLBoolFalse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Bool `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLBoolFalse) Reset() {
	*x = TLBoolFalse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLBoolFalse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLBoolFalse) ProtoMessage() {}

func (x *TLBoolFalse) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLBoolFalse.ProtoReflect.Descriptor instead.
func (*TLBoolFalse) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{1}
}

func (x *TLBoolFalse) GetData2() *Bool {
	if x != nil {
		return x.Data2
	}
	return nil
}

type TLBoolTrue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Bool `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLBoolTrue) Reset() {
	*x = TLBoolTrue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLBoolTrue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLBoolTrue) ProtoMessage() {}

func (x *TLBoolTrue) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLBoolTrue.ProtoReflect.Descriptor instead.
func (*TLBoolTrue) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{2}
}

func (x *TLBoolTrue) GetData2() *Bool {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Double <--
//   - TL_double
type Double struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	V             float64       `protobuf:"fixed64,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Double) Reset() {
	*x = Double{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Double) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Double) ProtoMessage() {}

func (x *Double) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Double.ProtoReflect.Descriptor instead.
func (*Double) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{3}
}

func (x *Double) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Double) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Double) GetV() float64 {
	if x != nil {
		return x.V
	}
	return 0
}

type TLDouble struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Double `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLDouble) Reset() {
	*x = TLDouble{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLDouble) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDouble) ProtoMessage() {}

func (x *TLDouble) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDouble.ProtoReflect.Descriptor instead.
func (*TLDouble) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{4}
}

func (x *TLDouble) GetData2() *Double {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Error <--
//   - TL_error
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Code          int32         `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	Text          string        `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Error) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Error) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Error) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type TLError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Error `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLError) Reset() {
	*x = TLError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLError) ProtoMessage() {}

func (x *TLError) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLError.ProtoReflect.Descriptor instead.
func (*TLError) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{6}
}

func (x *TLError) GetData2() *Error {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Int32 <--
//   - TL_int32
type Int32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	V             int32         `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Int32) Reset() {
	*x = Int32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int32) ProtoMessage() {}

func (x *Int32) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int32.ProtoReflect.Descriptor instead.
func (*Int32) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{7}
}

func (x *Int32) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Int32) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Int32) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

type TLInt32 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Int32 `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLInt32) Reset() {
	*x = TLInt32{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLInt32) ProtoMessage() {}

func (x *TLInt32) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLInt32.ProtoReflect.Descriptor instead.
func (*TLInt32) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{8}
}

func (x *TLInt32) GetData2() *Int32 {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Int64 <--
//   - TL_long
//   - TL_int64
type Int64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	V             int64         `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *Int64) Reset() {
	*x = Int64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Int64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Int64) ProtoMessage() {}

func (x *Int64) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Int64.ProtoReflect.Descriptor instead.
func (*Int64) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{9}
}

func (x *Int64) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Int64) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *Int64) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

type TLLong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Int64 `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLLong) Reset() {
	*x = TLLong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLLong) ProtoMessage() {}

func (x *TLLong) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLLong.ProtoReflect.Descriptor instead.
func (*TLLong) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{10}
}

func (x *TLLong) GetData2() *Int64 {
	if x != nil {
		return x.Data2
	}
	return nil
}

type TLInt64 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Int64 `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLInt64) Reset() {
	*x = TLInt64{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLInt64) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLInt64) ProtoMessage() {}

func (x *TLInt64) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLInt64.ProtoReflect.Descriptor instead.
func (*TLInt64) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{11}
}

func (x *TLInt64) GetData2() *Int64 {
	if x != nil {
		return x.Data2
	}
	return nil
}

// Null <--
//   - TL_null
type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{12}
}

func (x *Null) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *Null) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

type TLNull struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *Null `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLNull) Reset() {
	*x = TLNull{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLNull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLNull) ProtoMessage() {}

func (x *TLNull) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLNull.ProtoReflect.Descriptor instead.
func (*TLNull) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{13}
}

func (x *TLNull) GetData2() *Null {
	if x != nil {
		return x.Data2
	}
	return nil
}

// String <--
//   - TL_string
type String struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	V             string        `protobuf:"bytes,3,opt,name=v,proto3" json:"v,omitempty"`
}

func (x *String) Reset() {
	*x = String{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *String) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*String) ProtoMessage() {}

func (x *String) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use String.ProtoReflect.Descriptor instead.
func (*String) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{14}
}

func (x *String) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *String) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *String) GetV() string {
	if x != nil {
		return x.V
	}
	return ""
}

type TLString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *String `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLString) Reset() {
	*x = TLString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLString) ProtoMessage() {}

func (x *TLString) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLString.ProtoReflect.Descriptor instead.
func (*TLString) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{15}
}

func (x *TLString) GetData2() *String {
	if x != nil {
		return x.Data2
	}
	return nil
}

// True <--
//   - TL_true
type True struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredicateName string        `protobuf:"bytes,1,opt,name=predicate_name,json=predicateName,proto3" json:"predicate_name,omitempty"`
	Constructor   TLConstructor `protobuf:"varint,2,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *True) Reset() {
	*x = True{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *True) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*True) ProtoMessage() {}

func (x *True) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use True.ProtoReflect.Descriptor instead.
func (*True) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{16}
}

func (x *True) GetPredicateName() string {
	if x != nil {
		return x.PredicateName
	}
	return ""
}

func (x *True) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

type TLTrue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data2 *True `protobuf:"bytes,1,opt,name=data2,proto3" json:"data2,omitempty"`
}

func (x *TLTrue) Reset() {
	*x = TLTrue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_core_types_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLTrue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLTrue) ProtoMessage() {}

func (x *TLTrue) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_core_types_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLTrue.ProtoReflect.Descriptor instead.
func (*TLTrue) Descriptor() ([]byte, []int) {
	return file_schema_tl_core_types_proto_rawDescGZIP(), []int{17}
}

func (x *TLTrue) GetData2() *True {
	if x != nil {
		return x.Data2
	}
	return nil
}

var File_schema_tl_core_types_proto protoreflect.FileDescriptor

var file_schema_tl_core_types_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x74, 0x6c, 0x2e, 0x63, 0x6f, 0x72, 0x65,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x74, 0x6c,
	0x2e, 0x63, 0x72, 0x63, 0x33, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x04,
	0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72,
	0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x0c, 0x54, 0x4c, 0x5f, 0x62, 0x6f, 0x6f, 0x6c,
	0x46, 0x61, 0x6c, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42,
	0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x32, 0x0a, 0x0b, 0x54, 0x4c,
	0x5f, 0x62, 0x6f, 0x6f, 0x6c, 0x54, 0x72, 0x75, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x77,
	0x0a, 0x06, 0x44, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x76, 0x22, 0x32, 0x0a, 0x09, 0x54, 0x4c, 0x5f, 0x64, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f,
	0x75, 0x62, 0x6c, 0x65, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x90, 0x01, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x30,
	0x0a, 0x08, 0x54, 0x4c, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x24, 0x0a, 0x05, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32,
	0x22, 0x76, 0x0a, 0x05, 0x49, 0x6e, 0x74, 0x33, 0x32, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x01, 0x76, 0x22, 0x30, 0x0a, 0x08, 0x54, 0x4c, 0x5f, 0x69,
	0x6e, 0x74, 0x33, 0x32, 0x12, 0x24, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e,
	0x74, 0x33, 0x32, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x76, 0x0a, 0x05, 0x49, 0x6e,
	0x74, 0x36, 0x34, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x01, 0x76, 0x22, 0x2f, 0x0a, 0x07, 0x54, 0x4c, 0x5f, 0x6c, 0x6f, 0x6e, 0x67, 0x12, 0x24, 0x0a,
	0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d,
	0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x05, 0x64, 0x61,
	0x74, 0x61, 0x32, 0x22, 0x30, 0x0a, 0x08, 0x54, 0x4c, 0x5f, 0x69, 0x6e, 0x74, 0x36, 0x34, 0x12,
	0x24, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x74, 0x36, 0x34, 0x52, 0x05,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x67, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x12, 0x25, 0x0a,
	0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x2e,
	0x0a, 0x07, 0x54, 0x4c, 0x5f, 0x6e, 0x75, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x77,
	0x0a, 0x06, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x01, 0x76, 0x22, 0x32, 0x0a, 0x09, 0x54, 0x4c, 0x5f, 0x73, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x25, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x52, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x22, 0x67, 0x0a, 0x04, 0x54,
	0x72, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x07, 0x54, 0x4c, 0x5f, 0x74, 0x72, 0x75, 0x65, 0x12,
	0x23, 0x0a, 0x05, 0x64, 0x61, 0x74, 0x61, 0x32, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x72, 0x75, 0x65, 0x52, 0x05, 0x64,
	0x61, 0x74, 0x61, 0x32, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x67, 0x72, 0x61, 0x6d, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_schema_tl_core_types_proto_rawDescOnce sync.Once
	file_schema_tl_core_types_proto_rawDescData = file_schema_tl_core_types_proto_rawDesc
)

func file_schema_tl_core_types_proto_rawDescGZIP() []byte {
	file_schema_tl_core_types_proto_rawDescOnce.Do(func() {
		file_schema_tl_core_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_tl_core_types_proto_rawDescData)
	})
	return file_schema_tl_core_types_proto_rawDescData
}

var file_schema_tl_core_types_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_schema_tl_core_types_proto_goTypes = []any{
	(*Bool)(nil),        // 0: mtproto.Bool
	(*TLBoolFalse)(nil), // 1: mtproto.TL_boolFalse
	(*TLBoolTrue)(nil),  // 2: mtproto.TL_boolTrue
	(*Double)(nil),      // 3: mtproto.Double
	(*TLDouble)(nil),    // 4: mtproto.TL_double
	(*Error)(nil),       // 5: mtproto.Error
	(*TLError)(nil),     // 6: mtproto.TL_error
	(*Int32)(nil),       // 7: mtproto.Int32
	(*TLInt32)(nil),     // 8: mtproto.TL_int32
	(*Int64)(nil),       // 9: mtproto.Int64
	(*TLLong)(nil),      // 10: mtproto.TL_long
	(*TLInt64)(nil),     // 11: mtproto.TL_int64
	(*Null)(nil),        // 12: mtproto.Null
	(*TLNull)(nil),      // 13: mtproto.TL_null
	(*String)(nil),      // 14: mtproto.String
	(*TLString)(nil),    // 15: mtproto.TL_string
	(*True)(nil),        // 16: mtproto.True
	(*TLTrue)(nil),      // 17: mtproto.TL_true
	(TLConstructor)(0),  // 18: mtproto.TLConstructor
}
var file_schema_tl_core_types_proto_depIdxs = []int32{
	18, // 0: mtproto.Bool.constructor:type_name -> mtproto.TLConstructor
	0,  // 1: mtproto.TL_boolFalse.data2:type_name -> mtproto.Bool
	0,  // 2: mtproto.TL_boolTrue.data2:type_name -> mtproto.Bool
	18, // 3: mtproto.Double.constructor:type_name -> mtproto.TLConstructor
	3,  // 4: mtproto.TL_double.data2:type_name -> mtproto.Double
	18, // 5: mtproto.Error.constructor:type_name -> mtproto.TLConstructor
	5,  // 6: mtproto.TL_error.data2:type_name -> mtproto.Error
	18, // 7: mtproto.Int32.constructor:type_name -> mtproto.TLConstructor
	7,  // 8: mtproto.TL_int32.data2:type_name -> mtproto.Int32
	18, // 9: mtproto.Int64.constructor:type_name -> mtproto.TLConstructor
	9,  // 10: mtproto.TL_long.data2:type_name -> mtproto.Int64
	9,  // 11: mtproto.TL_int64.data2:type_name -> mtproto.Int64
	18, // 12: mtproto.Null.constructor:type_name -> mtproto.TLConstructor
	12, // 13: mtproto.TL_null.data2:type_name -> mtproto.Null
	18, // 14: mtproto.String.constructor:type_name -> mtproto.TLConstructor
	14, // 15: mtproto.TL_string.data2:type_name -> mtproto.String
	18, // 16: mtproto.True.constructor:type_name -> mtproto.TLConstructor
	16, // 17: mtproto.TL_true.data2:type_name -> mtproto.True
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_schema_tl_core_types_proto_init() }
func file_schema_tl_core_types_proto_init() {
	if File_schema_tl_core_types_proto != nil {
		return
	}
	file_schema_tl_crc32_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_schema_tl_core_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Bool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TLBoolFalse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TLBoolTrue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Double); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TLDouble); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TLError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Int32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*TLInt32); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Int64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*TLLong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*TLInt64); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*TLNull); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*String); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*TLString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*True); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_core_types_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*TLTrue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_tl_core_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_tl_core_types_proto_goTypes,
		DependencyIndexes: file_schema_tl_core_types_proto_depIdxs,
		MessageInfos:      file_schema_tl_core_types_proto_msgTypes,
	}.Build()
	File_schema_tl_core_types_proto = out.File
	file_schema_tl_core_types_proto_rawDesc = nil
	file_schema_tl_core_types_proto_goTypes = nil
	file_schema_tl_core_types_proto_depIdxs = nil
}
