//
// WARNING! All changes made in this file will be lost!
// Created from 'scheme.tl' by 'mtprotoc'
//
// Copyright (c) 2025-present,  Teamgram Authors.
//  All rights reserved.
//
// Author: Benqi (wubenqi@gmail.com)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.26.1
// source: schema.tl.transport_service.proto

package mtproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLRpcDropAnswer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	ReqMsgId    int64         `protobuf:"varint,3,opt,name=req_msg_id,json=reqMsgId,proto3" json:"req_msg_id,omitempty"`
}

func (x *TLRpcDropAnswer) Reset() {
	*x = TLRpcDropAnswer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLRpcDropAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLRpcDropAnswer) ProtoMessage() {}

func (x *TLRpcDropAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLRpcDropAnswer.ProtoReflect.Descriptor instead.
func (*TLRpcDropAnswer) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{0}
}

func (x *TLRpcDropAnswer) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLRpcDropAnswer) GetReqMsgId() int64 {
	if x != nil {
		return x.ReqMsgId
	}
	return 0
}

type TLGetFutureSalts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Num         int32         `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *TLGetFutureSalts) Reset() {
	*x = TLGetFutureSalts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLGetFutureSalts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLGetFutureSalts) ProtoMessage() {}

func (x *TLGetFutureSalts) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLGetFutureSalts.ProtoReflect.Descriptor instead.
func (*TLGetFutureSalts) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{1}
}

func (x *TLGetFutureSalts) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLGetFutureSalts) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type TLPing struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	PingId      int64         `protobuf:"varint,3,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
}

func (x *TLPing) Reset() {
	*x = TLPing{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLPing) ProtoMessage() {}

func (x *TLPing) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLPing.ProtoReflect.Descriptor instead.
func (*TLPing) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{2}
}

func (x *TLPing) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLPing) GetPingId() int64 {
	if x != nil {
		return x.PingId
	}
	return 0
}

type TLPingDelayDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor     TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	PingId          int64         `protobuf:"varint,3,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	DisconnectDelay int32         `protobuf:"varint,4,opt,name=disconnect_delay,json=disconnectDelay,proto3" json:"disconnect_delay,omitempty"`
}

func (x *TLPingDelayDisconnect) Reset() {
	*x = TLPingDelayDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLPingDelayDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLPingDelayDisconnect) ProtoMessage() {}

func (x *TLPingDelayDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLPingDelayDisconnect.ProtoReflect.Descriptor instead.
func (*TLPingDelayDisconnect) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{3}
}

func (x *TLPingDelayDisconnect) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLPingDelayDisconnect) GetPingId() int64 {
	if x != nil {
		return x.PingId
	}
	return 0
}

func (x *TLPingDelayDisconnect) GetDisconnectDelay() int32 {
	if x != nil {
		return x.DisconnectDelay
	}
	return 0
}

type TLDestroySession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	SessionId   int64         `protobuf:"varint,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
}

func (x *TLDestroySession) Reset() {
	*x = TLDestroySession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLDestroySession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLDestroySession) ProtoMessage() {}

func (x *TLDestroySession) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLDestroySession.ProtoReflect.Descriptor instead.
func (*TLDestroySession) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{4}
}

func (x *TLDestroySession) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

func (x *TLDestroySession) GetSessionId() int64 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type TLTestUseError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *TLTestUseError) Reset() {
	*x = TLTestUseError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLTestUseError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLTestUseError) ProtoMessage() {}

func (x *TLTestUseError) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLTestUseError.ProtoReflect.Descriptor instead.
func (*TLTestUseError) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{5}
}

func (x *TLTestUseError) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

type TLTestUseConfigSimple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *TLTestUseConfigSimple) Reset() {
	*x = TLTestUseConfigSimple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLTestUseConfigSimple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLTestUseConfigSimple) ProtoMessage() {}

func (x *TLTestUseConfigSimple) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLTestUseConfigSimple.ProtoReflect.Descriptor instead.
func (*TLTestUseConfigSimple) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{6}
}

func (x *TLTestUseConfigSimple) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

type TLTestParseInputAppEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Constructor TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
}

func (x *TLTestParseInputAppEvent) Reset() {
	*x = TLTestParseInputAppEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_tl_transport_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TLTestParseInputAppEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLTestParseInputAppEvent) ProtoMessage() {}

func (x *TLTestParseInputAppEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schema_tl_transport_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLTestParseInputAppEvent.ProtoReflect.Descriptor instead.
func (*TLTestParseInputAppEvent) Descriptor() ([]byte, []int) {
	return file_schema_tl_transport_service_proto_rawDescGZIP(), []int{7}
}

func (x *TLTestParseInputAppEvent) GetConstructor() TLConstructor {
	if x != nil {
		return x.Constructor
	}
	return TLConstructor_CRC32_UNKNOWN
}

var File_schema_tl_transport_service_proto protoreflect.FileDescriptor

var file_schema_tl_transport_service_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x74, 0x6c, 0x2e, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x73, 0x63,
	0x68, 0x65, 0x6d, 0x61, 0x2e, 0x74, 0x6c, 0x2e, 0x63, 0x72, 0x63, 0x33, 0x32, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x6c, 0x0a, 0x12, 0x54, 0x4c, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x64, 0x72,
	0x6f, 0x70, 0x5f, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16,
	0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63,
	0x74, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x5f, 0x6d, 0x73, 0x67, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x65, 0x71, 0x4d, 0x73, 0x67, 0x49,
	0x64, 0x22, 0x61, 0x0a, 0x13, 0x54, 0x4c, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x66, 0x75, 0x74, 0x75,
	0x72, 0x65, 0x5f, 0x73, 0x61, 0x6c, 0x74, 0x73, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e,
	0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x22, 0x5c, 0x0a, 0x07, 0x54, 0x4c, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x12,
	0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x22, 0x98, 0x01, 0x0a, 0x18, 0x54, 0x4c, 0x5f, 0x70, 0x69, 0x6e, 0x67, 0x5f, 0x64,
	0x65, 0x6c, 0x61, 0x79, 0x5f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12,
	0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f,
	0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x69, 0x6e,
	0x67, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x70, 0x69, 0x6e, 0x67,
	0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x5f, 0x64, 0x65, 0x6c, 0x61, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x44, 0x65, 0x6c, 0x61, 0x79, 0x22, 0x6d, 0x0a,
	0x12, 0x54, 0x4c, 0x5f, 0x64, 0x65, 0x73, 0x74, 0x72, 0x6f, 0x79, 0x5f, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72,
	0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x10,
	0x54, 0x4c, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x53, 0x0a, 0x17, 0x54, 0x4c,
	0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x75, 0x73, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53,
	0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x22,
	0x56, 0x0a, 0x1a, 0x54, 0x4c, 0x5f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x70, 0x61, 0x72, 0x73, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x70, 0x70, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x4c, 0x43,
	0x6f, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x67, 0x72, 0x61, 0x6d, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x74, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_tl_transport_service_proto_rawDescOnce sync.Once
	file_schema_tl_transport_service_proto_rawDescData = file_schema_tl_transport_service_proto_rawDesc
)

func file_schema_tl_transport_service_proto_rawDescGZIP() []byte {
	file_schema_tl_transport_service_proto_rawDescOnce.Do(func() {
		file_schema_tl_transport_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_tl_transport_service_proto_rawDescData)
	})
	return file_schema_tl_transport_service_proto_rawDescData
}

var file_schema_tl_transport_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_schema_tl_transport_service_proto_goTypes = []any{
	(*TLRpcDropAnswer)(nil),          // 0: mtproto.TL_rpc_drop_answer
	(*TLGetFutureSalts)(nil),         // 1: mtproto.TL_get_future_salts
	(*TLPing)(nil),                   // 2: mtproto.TL_ping
	(*TLPingDelayDisconnect)(nil),    // 3: mtproto.TL_ping_delay_disconnect
	(*TLDestroySession)(nil),         // 4: mtproto.TL_destroy_session
	(*TLTestUseError)(nil),           // 5: mtproto.TL_test_useError
	(*TLTestUseConfigSimple)(nil),    // 6: mtproto.TL_test_useConfigSimple
	(*TLTestParseInputAppEvent)(nil), // 7: mtproto.TL_test_parseInputAppEvent
	(TLConstructor)(0),               // 8: mtproto.TLConstructor
}
var file_schema_tl_transport_service_proto_depIdxs = []int32{
	8, // 0: mtproto.TL_rpc_drop_answer.constructor:type_name -> mtproto.TLConstructor
	8, // 1: mtproto.TL_get_future_salts.constructor:type_name -> mtproto.TLConstructor
	8, // 2: mtproto.TL_ping.constructor:type_name -> mtproto.TLConstructor
	8, // 3: mtproto.TL_ping_delay_disconnect.constructor:type_name -> mtproto.TLConstructor
	8, // 4: mtproto.TL_destroy_session.constructor:type_name -> mtproto.TLConstructor
	8, // 5: mtproto.TL_test_useError.constructor:type_name -> mtproto.TLConstructor
	8, // 6: mtproto.TL_test_useConfigSimple.constructor:type_name -> mtproto.TLConstructor
	8, // 7: mtproto.TL_test_parseInputAppEvent.constructor:type_name -> mtproto.TLConstructor
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_schema_tl_transport_service_proto_init() }
func file_schema_tl_transport_service_proto_init() {
	if File_schema_tl_transport_service_proto != nil {
		return
	}
	file_schema_tl_crc32_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_schema_tl_transport_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TLRpcDropAnswer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*TLGetFutureSalts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*TLPing); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*TLPingDelayDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*TLDestroySession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*TLTestUseError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*TLTestUseConfigSimple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_schema_tl_transport_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TLTestParseInputAppEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_tl_transport_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_tl_transport_service_proto_goTypes,
		DependencyIndexes: file_schema_tl_transport_service_proto_depIdxs,
		MessageInfos:      file_schema_tl_transport_service_proto_msgTypes,
	}.Build()
	File_schema_tl_transport_service_proto = out.File
	file_schema_tl_transport_service_proto_rawDesc = nil
	file_schema_tl_transport_service_proto_goTypes = nil
	file_schema_tl_transport_service_proto_depIdxs = nil
}
